### ISSUE TITLE
ifort (Intel Fortran)

### ISSUE THREAD

**Issue by idealistisch** [AtomLinter/linter-gfortran#12]
I was wondering if it is possible to use the ifort instead of gfortran in the Atom linter. Is that possible?

**Comment by Luthaf** [comment]
As I said in the email, this should just work if ifort accept the same flags as gfortran and the console output is similar.

Else, it should be pretty easy to add with a setting to switch between the compilers. If someone with access to ifort want to do this, I can help a bit.

**Comment by idealistisch** [comment]
I tried to change the executable path to "ifort" and to the installation dir. Also, I tried -CB, -g and -debug all as flags. Nothing happened.

Maybe I can help, but I will need some help to do this.

**Comment by Luthaf** [comment]
Great! This package works by running the compiler on a temporary copy of the current file, and then parsing the compiler output to find the errors/warnings.

There are two places to modify: the [regex](https://github.com/AtomLinter/linter-gfortran/blob/0090eae95b3a90f70e3718a52ec7f5b142cf7503/lib/main.js#L22) used to match the output of the compiler, and the [flags](https://github.com/AtomLinter/linter-gfortran/blob/0090eae95b3a90f70e3718a52ec7f5b142cf7503/lib/main.js#L41-L46) passed to the compiler.

To implement this, I would add a setting to the package, and then change the regex and the flags depending on this setting.

**Comment by Arcanemagus** [comment]
If you wanted to create your own provider for `ifort` (possibly forking this as a starting point), and need any help please let me know!
