### ISSUE TITLE
Support for "real" linter

### ISSUE THREAD

**Issue by cphyc** [AtomLinter/linter-gfortran#19]
Hi @Luthaf !

For your information, I wrote a Fortran linter in Python on my own that does 'real' linting and not only grammar and syntax checking. For examples, it complains about missing spaces around expressions, the use of depreciated syntax, …
You can check it out here: https://github.com/cphyc/fortran-syntax.
I'd be glad to include a plugin for Atom!

**Comment by Luthaf** [comment]
Hey @cphyc, nice to see you again! 

Concerning your linter, it could be integrated within this package if the output looks like a standard compiler output (it might __*just work*__ if you set gfortran path to the linter path). 

I think the spirit of Atom linters is to have one package per linter, so having a separated package for your linter would make sense too.

I am not really working with fortran these days (only once every six months to update the [chemfiles bindings](https://github.com/chemfiles/chemfiles.f03)), so I might not be the main user of your code =). But I am sure other people would be very interested!

**Comment by cphyc** [comment]
So apparently the only point where there might be an issue is that my linter expects `FILENAME --syntax-only` to show the warnings. In the case of your package, it will pass `-fsyntax-only` as well as other `-J… -I…`, thus making my linter crash for unexpected arguments.
Those interested can just remove the lines https://github.com/AtomLinter/linter-gfortran/blob/60df8e63c59f1d894274d3cd7b4086c47a536507/lib/main.js#L55 to https://github.com/AtomLinter/linter-gfortran/blob/60df8e63c59f1d894274d3cd7b4086c47a536507/lib/main.js#L58, and customize the location of the linter to a path loading to the my python linter.

**Comment by Arcanemagus** [comment]
Closing this, if you wanted to create as provider for your linter and need help just let me know!
