### ISSUE TITLE
Error Running Gfortran

### ISSUE THREAD

**Issue by gwgwhc** [AtomLinter/linter-gfortran#20]
I just installed gfortran 6.4.0 through cygwin on my win10 pc and the code is compiling and running in the cygwin terminal. Atom however says that there is an error running gfortran. Any idea why?
Thanks in advance.

```
Error running gfortran Error: spawn gfortran ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by Arcanemagus** [comment]
`gfortran` needs to be available on your `%PATH%` for the default settings to work within Atom. This means that if you open a Command Prompt (_not_ a `cygwin` shell) and type `where.exe gfortran` you should get back a path. 

If you _just_ installed it, it's possible that you need to completely shut down Atom and start it back up again for it to pick up your updated `%PATH%`.

If `where.exe` returns a path and you have restarted Atom it _should_ be working, if not though you can always explicitly set the path with the "Executable" setting for this package.
