### ISSUE TITLE
Allow per-project compiler

### ISSUE THREAD

**Issue by marmistrz** [AtomLinter/linter-gfortran#4]
When working on an MPI project, I'll use `mpif90`, otherwise simple `gfortran`

**Comment by Luthaf** [comment]
Why not set the compiler to `mpif90` globally? It should be able to parse and check standard Fortran code too.

**Comment by Arcanemagus** [comment]
For per-project settings in other linters we defer people to [project-manager](https://atom.io/packages/project-manager) (at least until Atom finally brings in support natively for per-project settings).

**Comment by Arcanemagus** [comment]
I'm going to mark this as closed based on the availability of `project-manager`, if for some reason that isn't going to fulfill your needs @marmistrz please comment back!
